### ISSUE TITLE
추천: boilerplate

### ISSUE THREAD

**Issue by ChangJoo-Park** [EndlessCreation/tastynote-webclient#1]
npm을 사용할 수 있는 상황이면 yo를 이용해서 프로젝트를 시작하는 걸 추천해

사용하기 힘든 환경이면 아래 프로젝트에서 기본 코드들을 어떻게 구성하는지 보는게 도움이 될거라고 생각하고..
https://github.com/ChangJoo-Park/angular-meteor-material-boilerplate

yo를 사용하는게 부담이 적게되면 
- https://github.com/ndxbxrme/generator-angular-meteor
- https://github.com/damirkusar/generator-catena-angular-meteor-material

이 두 프로젝트 한번 봐

**Comment by JuhoKang** [comment]
오 yo generater가 있군요. 한번 해볼게요 될련지 안될련지 모르겠지만

생각해보니 이전에 jhipster라고 yo generator를 써봤는데 spring boot + angular 세팅 해주는 녀석이였는데 만들고 나서도 너무 복잡해서 애먹었던 기억이 떠오릅니다. 아마 될것 같습니다.

**Comment by ChangJoo-Park** [comment]
프로젝트 관리할 때 파일 관리를 어떻게 할 지 감이 안오는 경우가 있으면 다른사람들이 해놓은 구조 참고하려고 제너레이터를 찾아서 보거든 그리고 터미널에서 명령어로 조작할 수있는 걸 제공하는 경우는 더 좋고.. 모델이나 디렉티브, 컨트롤러 같은거 만들 때 유용하더라
